// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app

import (
	"context"
	"sync"
)

// Ensure, that ServerMock does implement Server.
// If this is not the case, regenerate this file with moq.
var _ Server = &ServerMock{}

// ServerMock is a mock implementation of Server.
//
//	func TestSomethingThatUsesServer(t *testing.T) {
//
//		// make and configure a mocked Server
//		mockedServer := &ServerMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			ListenAndServeFunc: func() error {
//				panic("mock out the ListenAndServe method")
//			},
//			ShutdownFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Shutdown method")
//			},
//		}
//
//		// use mockedServer in code that requires Server
//		// and then make assertions.
//
//	}
type ServerMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ListenAndServeFunc mocks the ListenAndServe method.
	ListenAndServeFunc func() error

	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func(contextMoqParam context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// ListenAndServe holds details about calls to the ListenAndServe method.
		ListenAndServe []struct {
		}
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockClose          sync.RWMutex
	lockListenAndServe sync.RWMutex
	lockShutdown       sync.RWMutex
}

// Close calls CloseFunc.
func (mock *ServerMock) Close() error {
	if mock.CloseFunc == nil {
		panic("ServerMock.CloseFunc: method is nil but Server.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedServer.CloseCalls())
func (mock *ServerMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// ListenAndServe calls ListenAndServeFunc.
func (mock *ServerMock) ListenAndServe() error {
	if mock.ListenAndServeFunc == nil {
		panic("ServerMock.ListenAndServeFunc: method is nil but Server.ListenAndServe was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListenAndServe.Lock()
	mock.calls.ListenAndServe = append(mock.calls.ListenAndServe, callInfo)
	mock.lockListenAndServe.Unlock()
	return mock.ListenAndServeFunc()
}

// ListenAndServeCalls gets all the calls that were made to ListenAndServe.
// Check the length with:
//
//	len(mockedServer.ListenAndServeCalls())
func (mock *ServerMock) ListenAndServeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListenAndServe.RLock()
	calls = mock.calls.ListenAndServe
	mock.lockListenAndServe.RUnlock()
	return calls
}

// Shutdown calls ShutdownFunc.
func (mock *ServerMock) Shutdown(contextMoqParam context.Context) error {
	if mock.ShutdownFunc == nil {
		panic("ServerMock.ShutdownFunc: method is nil but Server.Shutdown was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	return mock.ShutdownFunc(contextMoqParam)
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//
//	len(mockedServer.ShutdownCalls())
func (mock *ServerMock) ShutdownCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}
