// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package order

import (
	"context"
	"sync"
)

// Ensure, that OrderRepositoryMock does implement OrderRepository.
// If this is not the case, regenerate this file with moq.
var _ OrderRepository = &OrderRepositoryMock{}

// OrderRepositoryMock is a mock implementation of OrderRepository.
//
//	func TestSomethingThatUsesOrderRepository(t *testing.T) {
//
//		// make and configure a mocked OrderRepository
//		mockedOrderRepository := &OrderRepositoryMock{
//			CreateFunc: func(ctx context.Context, order Order) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetAllFunc: func(ctx context.Context) ([]Order, error) {
//				panic("mock out the GetAll method")
//			},
//			GetByIDFunc: func(ctx context.Context, id string) (Order, error) {
//				panic("mock out the GetByID method")
//			},
//			UpdateFunc: func(ctx context.Context, order Order) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedOrderRepository in code that requires OrderRepository
//		// and then make assertions.
//
//	}
type OrderRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, order Order) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]Order, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id string) (Order, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, order Order) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Order is the order argument value.
			Order Order
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Order is the order argument value.
			Order Order
		}
	}
	lockCreate  sync.RWMutex
	lockDelete  sync.RWMutex
	lockGetAll  sync.RWMutex
	lockGetByID sync.RWMutex
	lockUpdate  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *OrderRepositoryMock) Create(ctx context.Context, order Order) error {
	if mock.CreateFunc == nil {
		panic("OrderRepositoryMock.CreateFunc: method is nil but OrderRepository.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Order Order
	}{
		Ctx:   ctx,
		Order: order,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, order)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedOrderRepository.CreateCalls())
func (mock *OrderRepositoryMock) CreateCalls() []struct {
	Ctx   context.Context
	Order Order
} {
	var calls []struct {
		Ctx   context.Context
		Order Order
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *OrderRepositoryMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("OrderRepositoryMock.DeleteFunc: method is nil but OrderRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedOrderRepository.DeleteCalls())
func (mock *OrderRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *OrderRepositoryMock) GetAll(ctx context.Context) ([]Order, error) {
	if mock.GetAllFunc == nil {
		panic("OrderRepositoryMock.GetAllFunc: method is nil but OrderRepository.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedOrderRepository.GetAllCalls())
func (mock *OrderRepositoryMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *OrderRepositoryMock) GetByID(ctx context.Context, id string) (Order, error) {
	if mock.GetByIDFunc == nil {
		panic("OrderRepositoryMock.GetByIDFunc: method is nil but OrderRepository.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedOrderRepository.GetByIDCalls())
func (mock *OrderRepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *OrderRepositoryMock) Update(ctx context.Context, order Order) error {
	if mock.UpdateFunc == nil {
		panic("OrderRepositoryMock.UpdateFunc: method is nil but OrderRepository.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Order Order
	}{
		Ctx:   ctx,
		Order: order,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, order)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedOrderRepository.UpdateCalls())
func (mock *OrderRepositoryMock) UpdateCalls() []struct {
	Ctx   context.Context
	Order Order
} {
	var calls []struct {
		Ctx   context.Context
		Order Order
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that EventPublisherMock does implement EventPublisher.
// If this is not the case, regenerate this file with moq.
var _ EventPublisher = &EventPublisherMock{}

// EventPublisherMock is a mock implementation of EventPublisher.
//
//	func TestSomethingThatUsesEventPublisher(t *testing.T) {
//
//		// make and configure a mocked EventPublisher
//		mockedEventPublisher := &EventPublisherMock{
//			PublishOrderCreatedFunc: func(ctx context.Context, order Order) error {
//				panic("mock out the PublishOrderCreated method")
//			},
//			PublishOrderDeletedFunc: func(ctx context.Context, id string) error {
//				panic("mock out the PublishOrderDeleted method")
//			},
//			PublishOrderUpdatedFunc: func(ctx context.Context, order Order) error {
//				panic("mock out the PublishOrderUpdated method")
//			},
//		}
//
//		// use mockedEventPublisher in code that requires EventPublisher
//		// and then make assertions.
//
//	}
type EventPublisherMock struct {
	// PublishOrderCreatedFunc mocks the PublishOrderCreated method.
	PublishOrderCreatedFunc func(ctx context.Context, order Order) error

	// PublishOrderDeletedFunc mocks the PublishOrderDeleted method.
	PublishOrderDeletedFunc func(ctx context.Context, id string) error

	// PublishOrderUpdatedFunc mocks the PublishOrderUpdated method.
	PublishOrderUpdatedFunc func(ctx context.Context, order Order) error

	// calls tracks calls to the methods.
	calls struct {
		// PublishOrderCreated holds details about calls to the PublishOrderCreated method.
		PublishOrderCreated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Order is the order argument value.
			Order Order
		}
		// PublishOrderDeleted holds details about calls to the PublishOrderDeleted method.
		PublishOrderDeleted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// PublishOrderUpdated holds details about calls to the PublishOrderUpdated method.
		PublishOrderUpdated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Order is the order argument value.
			Order Order
		}
	}
	lockPublishOrderCreated sync.RWMutex
	lockPublishOrderDeleted sync.RWMutex
	lockPublishOrderUpdated sync.RWMutex
}

// PublishOrderCreated calls PublishOrderCreatedFunc.
func (mock *EventPublisherMock) PublishOrderCreated(ctx context.Context, order Order) error {
	if mock.PublishOrderCreatedFunc == nil {
		panic("EventPublisherMock.PublishOrderCreatedFunc: method is nil but EventPublisher.PublishOrderCreated was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Order Order
	}{
		Ctx:   ctx,
		Order: order,
	}
	mock.lockPublishOrderCreated.Lock()
	mock.calls.PublishOrderCreated = append(mock.calls.PublishOrderCreated, callInfo)
	mock.lockPublishOrderCreated.Unlock()
	return mock.PublishOrderCreatedFunc(ctx, order)
}

// PublishOrderCreatedCalls gets all the calls that were made to PublishOrderCreated.
// Check the length with:
//
//	len(mockedEventPublisher.PublishOrderCreatedCalls())
func (mock *EventPublisherMock) PublishOrderCreatedCalls() []struct {
	Ctx   context.Context
	Order Order
} {
	var calls []struct {
		Ctx   context.Context
		Order Order
	}
	mock.lockPublishOrderCreated.RLock()
	calls = mock.calls.PublishOrderCreated
	mock.lockPublishOrderCreated.RUnlock()
	return calls
}

// PublishOrderDeleted calls PublishOrderDeletedFunc.
func (mock *EventPublisherMock) PublishOrderDeleted(ctx context.Context, id string) error {
	if mock.PublishOrderDeletedFunc == nil {
		panic("EventPublisherMock.PublishOrderDeletedFunc: method is nil but EventPublisher.PublishOrderDeleted was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockPublishOrderDeleted.Lock()
	mock.calls.PublishOrderDeleted = append(mock.calls.PublishOrderDeleted, callInfo)
	mock.lockPublishOrderDeleted.Unlock()
	return mock.PublishOrderDeletedFunc(ctx, id)
}

// PublishOrderDeletedCalls gets all the calls that were made to PublishOrderDeleted.
// Check the length with:
//
//	len(mockedEventPublisher.PublishOrderDeletedCalls())
func (mock *EventPublisherMock) PublishOrderDeletedCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockPublishOrderDeleted.RLock()
	calls = mock.calls.PublishOrderDeleted
	mock.lockPublishOrderDeleted.RUnlock()
	return calls
}

// PublishOrderUpdated calls PublishOrderUpdatedFunc.
func (mock *EventPublisherMock) PublishOrderUpdated(ctx context.Context, order Order) error {
	if mock.PublishOrderUpdatedFunc == nil {
		panic("EventPublisherMock.PublishOrderUpdatedFunc: method is nil but EventPublisher.PublishOrderUpdated was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Order Order
	}{
		Ctx:   ctx,
		Order: order,
	}
	mock.lockPublishOrderUpdated.Lock()
	mock.calls.PublishOrderUpdated = append(mock.calls.PublishOrderUpdated, callInfo)
	mock.lockPublishOrderUpdated.Unlock()
	return mock.PublishOrderUpdatedFunc(ctx, order)
}

// PublishOrderUpdatedCalls gets all the calls that were made to PublishOrderUpdated.
// Check the length with:
//
//	len(mockedEventPublisher.PublishOrderUpdatedCalls())
func (mock *EventPublisherMock) PublishOrderUpdatedCalls() []struct {
	Ctx   context.Context
	Order Order
} {
	var calls []struct {
		Ctx   context.Context
		Order Order
	}
	mock.lockPublishOrderUpdated.RLock()
	calls = mock.calls.PublishOrderUpdated
	mock.lockPublishOrderUpdated.RUnlock()
	return calls
}
