// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package httpapi

import (
	"context"
	domain "github.com/shvadoodi/lecture-order-demo/internal/order"
	"sync"
)

// Ensure, that OrderServiceMock does implement OrderService.
// If this is not the case, regenerate this file with moq.
var _ OrderService = &OrderServiceMock{}

// OrderServiceMock is a mock implementation of OrderService.
//
//	func TestSomethingThatUsesOrderService(t *testing.T) {
//
//		// make and configure a mocked OrderService
//		mockedOrderService := &OrderServiceMock{
//			CreateOrderFunc: func(ctx context.Context, request domain.CreateOrderRequest) (domain.Order, error) {
//				panic("mock out the CreateOrder method")
//			},
//			DeleteOrderFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeleteOrder method")
//			},
//			GetOrderFunc: func(ctx context.Context, id string) (domain.Order, error) {
//				panic("mock out the GetOrder method")
//			},
//			GetOrdersFunc: func(ctx context.Context) ([]domain.Order, error) {
//				panic("mock out the GetOrders method")
//			},
//			UpdateOrderFunc: func(ctx context.Context, id string, request domain.UpdateOrderRequest) (domain.Order, error) {
//				panic("mock out the UpdateOrder method")
//			},
//		}
//
//		// use mockedOrderService in code that requires OrderService
//		// and then make assertions.
//
//	}
type OrderServiceMock struct {
	// CreateOrderFunc mocks the CreateOrder method.
	CreateOrderFunc func(ctx context.Context, request domain.CreateOrderRequest) (domain.Order, error)

	// DeleteOrderFunc mocks the DeleteOrder method.
	DeleteOrderFunc func(ctx context.Context, id string) error

	// GetOrderFunc mocks the GetOrder method.
	GetOrderFunc func(ctx context.Context, id string) (domain.Order, error)

	// GetOrdersFunc mocks the GetOrders method.
	GetOrdersFunc func(ctx context.Context) ([]domain.Order, error)

	// UpdateOrderFunc mocks the UpdateOrder method.
	UpdateOrderFunc func(ctx context.Context, id string, request domain.UpdateOrderRequest) (domain.Order, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrder holds details about calls to the CreateOrder method.
		CreateOrder []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Request is the request argument value.
			Request domain.CreateOrderRequest
		}
		// DeleteOrder holds details about calls to the DeleteOrder method.
		DeleteOrder []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetOrder holds details about calls to the GetOrder method.
		GetOrder []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetOrders holds details about calls to the GetOrders method.
		GetOrders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateOrder holds details about calls to the UpdateOrder method.
		UpdateOrder []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Request is the request argument value.
			Request domain.UpdateOrderRequest
		}
	}
	lockCreateOrder sync.RWMutex
	lockDeleteOrder sync.RWMutex
	lockGetOrder    sync.RWMutex
	lockGetOrders   sync.RWMutex
	lockUpdateOrder sync.RWMutex
}

// CreateOrder calls CreateOrderFunc.
func (mock *OrderServiceMock) CreateOrder(ctx context.Context, request domain.CreateOrderRequest) (domain.Order, error) {
	if mock.CreateOrderFunc == nil {
		panic("OrderServiceMock.CreateOrderFunc: method is nil but OrderService.CreateOrder was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Request domain.CreateOrderRequest
	}{
		Ctx:     ctx,
		Request: request,
	}
	mock.lockCreateOrder.Lock()
	mock.calls.CreateOrder = append(mock.calls.CreateOrder, callInfo)
	mock.lockCreateOrder.Unlock()
	return mock.CreateOrderFunc(ctx, request)
}

// CreateOrderCalls gets all the calls that were made to CreateOrder.
// Check the length with:
//
//	len(mockedOrderService.CreateOrderCalls())
func (mock *OrderServiceMock) CreateOrderCalls() []struct {
	Ctx     context.Context
	Request domain.CreateOrderRequest
} {
	var calls []struct {
		Ctx     context.Context
		Request domain.CreateOrderRequest
	}
	mock.lockCreateOrder.RLock()
	calls = mock.calls.CreateOrder
	mock.lockCreateOrder.RUnlock()
	return calls
}

// DeleteOrder calls DeleteOrderFunc.
func (mock *OrderServiceMock) DeleteOrder(ctx context.Context, id string) error {
	if mock.DeleteOrderFunc == nil {
		panic("OrderServiceMock.DeleteOrderFunc: method is nil but OrderService.DeleteOrder was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteOrder.Lock()
	mock.calls.DeleteOrder = append(mock.calls.DeleteOrder, callInfo)
	mock.lockDeleteOrder.Unlock()
	return mock.DeleteOrderFunc(ctx, id)
}

// DeleteOrderCalls gets all the calls that were made to DeleteOrder.
// Check the length with:
//
//	len(mockedOrderService.DeleteOrderCalls())
func (mock *OrderServiceMock) DeleteOrderCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeleteOrder.RLock()
	calls = mock.calls.DeleteOrder
	mock.lockDeleteOrder.RUnlock()
	return calls
}

// GetOrder calls GetOrderFunc.
func (mock *OrderServiceMock) GetOrder(ctx context.Context, id string) (domain.Order, error) {
	if mock.GetOrderFunc == nil {
		panic("OrderServiceMock.GetOrderFunc: method is nil but OrderService.GetOrder was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetOrder.Lock()
	mock.calls.GetOrder = append(mock.calls.GetOrder, callInfo)
	mock.lockGetOrder.Unlock()
	return mock.GetOrderFunc(ctx, id)
}

// GetOrderCalls gets all the calls that were made to GetOrder.
// Check the length with:
//
//	len(mockedOrderService.GetOrderCalls())
func (mock *OrderServiceMock) GetOrderCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetOrder.RLock()
	calls = mock.calls.GetOrder
	mock.lockGetOrder.RUnlock()
	return calls
}

// GetOrders calls GetOrdersFunc.
func (mock *OrderServiceMock) GetOrders(ctx context.Context) ([]domain.Order, error) {
	if mock.GetOrdersFunc == nil {
		panic("OrderServiceMock.GetOrdersFunc: method is nil but OrderService.GetOrders was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetOrders.Lock()
	mock.calls.GetOrders = append(mock.calls.GetOrders, callInfo)
	mock.lockGetOrders.Unlock()
	return mock.GetOrdersFunc(ctx)
}

// GetOrdersCalls gets all the calls that were made to GetOrders.
// Check the length with:
//
//	len(mockedOrderService.GetOrdersCalls())
func (mock *OrderServiceMock) GetOrdersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetOrders.RLock()
	calls = mock.calls.GetOrders
	mock.lockGetOrders.RUnlock()
	return calls
}

// UpdateOrder calls UpdateOrderFunc.
func (mock *OrderServiceMock) UpdateOrder(ctx context.Context, id string, request domain.UpdateOrderRequest) (domain.Order, error) {
	if mock.UpdateOrderFunc == nil {
		panic("OrderServiceMock.UpdateOrderFunc: method is nil but OrderService.UpdateOrder was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      string
		Request domain.UpdateOrderRequest
	}{
		Ctx:     ctx,
		ID:      id,
		Request: request,
	}
	mock.lockUpdateOrder.Lock()
	mock.calls.UpdateOrder = append(mock.calls.UpdateOrder, callInfo)
	mock.lockUpdateOrder.Unlock()
	return mock.UpdateOrderFunc(ctx, id, request)
}

// UpdateOrderCalls gets all the calls that were made to UpdateOrder.
// Check the length with:
//
//	len(mockedOrderService.UpdateOrderCalls())
func (mock *OrderServiceMock) UpdateOrderCalls() []struct {
	Ctx     context.Context
	ID      string
	Request domain.UpdateOrderRequest
} {
	var calls []struct {
		Ctx     context.Context
		ID      string
		Request domain.UpdateOrderRequest
	}
	mock.lockUpdateOrder.RLock()
	calls = mock.calls.UpdateOrder
	mock.lockUpdateOrder.RUnlock()
	return calls
}
